"""
retriever/query_expander.py
───────────────────────────
Step 1 of the retrieval pipeline: Query expansion + max-pool embedding.

What this module does
---------------------
1. Calls Claude Haiku to decompose the user's query into N sub-questions
   that cover different facets of the same information need.
2. Embeds the original query AND every sub-question using the shared
   SentenceTransformer model.
3. Returns a single max-pooled vector that has high similarity to ALL
   query variants, giving downstream Qdrant search broader semantic coverage.

Failure handling
----------------
If the Haiku API call fails for any reason (network, auth, parse error),
the module falls back silently to embedding the original query only.
This means query expansion is a best-effort enrichment, never a hard dependency.

Why Haiku for expansion?
------------------------
Haiku is ~10× cheaper and ~5× faster than Sonnet for this task.
Sub-question generation needs creativity, not depth — Haiku is ideal.
The final answer is still generated by Sonnet.
"""

from __future__ import annotations

import json
import logging
import re

from .config import EXPANSION_ENABLED, MAX_SUBQUESTIONS
from .math_utils import max_pool
from .singletons import _get_encoder

log = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Prompt
# ─────────────────────────────────────────────────────────────────────────────

_EXPANSION_PROMPT = """\
You are a search query expander. Given the user's question, generate {n} alternative
phrasings or sub-questions that capture different facets of the same information need.

Output ONLY a JSON array of strings. No explanation. No preamble. No markdown fences.
Example: ["alternative phrasing 1", "sub-question 2", "related angle 3"]

User question: {query}"""


# ─────────────────────────────────────────────────────────────────────────────
# Public functions
# ─────────────────────────────────────────────────────────────────────────────

def expand_query(query: str, n: int = MAX_SUBQUESTIONS) -> list[str]:
    """
    Generate sub-questions for *query* via Claude Haiku.

    Returns a list starting with the original query, followed by sub-questions.
    Falls back to [query] alone on any error.
    """
    if not EXPANSION_ENABLED:
        return [query]

    try:
        import anthropic
    except ImportError:
        log.warning("anthropic SDK not installed — skipping query expansion.")
        return [query]

    try:
        client = anthropic.Anthropic()
        resp   = client.messages.create(
            model      = "claude-haiku-4-5-20251001",
            max_tokens = 256,
            messages   = [{
                "role":    "user",
                "content": _EXPANSION_PROMPT.format(n=n, query=query),
            }],
        )
        raw = resp.content[0].text.strip()

        # Strip markdown code fences if the model added them despite instructions
        raw = re.sub(r"^```[a-z]*\s*", "", raw)
        raw = re.sub(r"\s*```$",        "", raw)

        alts = json.loads(raw)
        if isinstance(alts, list) and alts:
            variants = [query] + [str(a) for a in alts[:n]]
            log.info("Query expanded: %d variant(s) generated.", len(variants) - 1)
            return variants

        log.warning("Expansion returned unexpected format — using original query.")

    except Exception as exc:
        log.warning("Query expansion failed (%s) — using original query only.", exc)

    return [query]


def embed_query(query: str, expand: bool = True) -> tuple[list[float], list[str]]:
    """
    Embed the query, optionally after expansion.

    Steps:
      1. If expand=True, generate sub-questions via expand_query().
      2. Encode all variants with the shared SentenceTransformer.
      3. Max-pool the resulting vectors into one representative vector.

    Returns
    -------
    (query_vector, variants)
      query_vector : list[float] — max-pooled embedding, same dim as MODEL_NAME
      variants     : list[str]  — all query strings that were embedded
    """
    encoder  = _get_encoder()
    variants = expand_query(query) if expand else [query]

    raw_vecs = encoder.encode(variants, show_progress_bar=False).tolist()
    pooled   = max_pool(raw_vecs)

    log.info(
        "Query embedded: %d variant(s), vector dim=%d",
        len(variants), len(pooled),
    )
    return pooled, variants
